import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Providers } from "./providers";
import { AutoConnectProvider } from "@/components/AutoConnectProvider";
import WalletConnectionProvider from "@/components/WalletConnectionProvider";
require("@solana/wallet-adapter-react-ui/styles.css");

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col`}>
        <WalletConnectionProvider>
          <AutoConnectProvider>
            <Providers>
              <Header />
              {children}
            </Providers>
          </AutoConnectProvider>
        </WalletConnectionProvider>
      </body>
    </html>
  );
}
